# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dm-drupal}
  s.version = "0.1.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Quinn Shanahan"]
  s.date = %q{2009-12-15}
  s.description = %q{A datamapper wrapper for a drupal database.. great for migrations}
  s.email = %q{q.shanahan@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "lib/drupal.rb",
     "lib/drupal/cck.rb",
     "lib/drupal/cck/builder.rb",
     "lib/drupal/cck/fields.rb",
     "lib/drupal/node.rb",
     "lib/drupal/user.rb"
  ]
  s.homepage = %q{http://github.com/quinn/dm-drupal}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Datamapper << Drupal}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

